apiVersion: v1
data:
  appscode-api-grpc-endpoint: {{ .Values.appscodeAPIGrpcEndpoint}}
  appscode-cluster-root-domain:  {{ .Values.appscodeClusterRootDomain }}
  appscode-api-http-endpoint: {{ .Values.appscodeAPIhttpEndpoint }}
  appscode-ns: {{ .Values.appscodeNs }}
  clusterName: {{ .Values.clusterName }}
kind: ConfigMap
metadata:
  labels:
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: '{{ template "fullname" . }}-fake-tiller'
