apiVersion: v1
data:
  appscode-cluster-root-domain: appscode.xyz
  appscode-ns: qacode
  cluster-name: h505
kind: ConfigMap
metadata:
  labels:
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: '{{ template "fullname" . }}-fake-tiller'
  namespace: '{{.Values.clustermetadata.namespace}}'
